before_script:
  - docker login docker.com -u $DOCKER_USER -p $DOCKER_PASS

image:
  name: http418infosec/adlab:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

# Ensure that your Gitlab CI variables are set for AWS
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
  AWS_DEFAULT_REGION: eu-west-2

cache:
  paths:
    - terraform/.terraform/plugins

# https://stackoverflow.com/a/65810302
before_script:
  - terraform --version
  - mkdir -p $HOME/.docker
  - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

stages:
  - validate
  - deploy
  - test
  - image
  - cleanup

validate_terraform:
  stage: validate
  when: manual #TESTING - REMOVE FOR PROD
  script:
    - cd terraform
    - terraform init 
    - terraform validate

deploy:
  stage: deploy
  #when: manual
  script:
    - cd terraform
    - terraform init 
    - terraform apply --auto-approve --var ENVIRONMENT=staging
    - terraform output --json > output.json
  artifacts:
    when: always
    # We need to cache some files to avoid errors when it comes to tearing down our infra. 
    # Due to the way TF works, it relies on various state files, which we need to cache from stage to stage!
    # https://stackoverflow.com/a/73780145
    paths:
      - $CI_PROJECT_DIR/terraform/terraform.tfstate.d
      - $CI_PROJECT_DIR/terraform/.terraform.lock.hcl
      - $CI_PROJECT_DIR/terraform/output.json
    expire_in: 1 week

inspec:
  before_script:
    - mkdir -p /etc/chef/accepted_licenses/
    - echo > /etc/chef/accepted_licenses/inspec
    - gem install inspec inspec-bin bigdecimal
  stage: test
  #when: manual
  allow_failure: true
  dependencies:
    - deploy
  script:
    - cd test && ./run.sh

create_image:
  image: python:3
  stage: image
  #when: manual
  before_script:
    - cd .
  script:
    - cd imager
    - pip install -r requirements.txt
    - python ./imager.py

# Lets make a re-usable piece of code to clean up all artefacts from this pipeline
# This means it will delete all of the infra regardless of success or failure.
# https://stackoverflow.com/questions/64205410/gitlab-ci-specify-that-job-c-should-run-after-job-b-if-job-a-fails
.cleanup_job: &cleanup_job
  stage: cleanup
  script:
    - cd terraform
    - terraform destroy --auto-approve --var ENVIRONMENT=staging

cleanup_build_success:
  stage: cleanup
  when: on_success
  <<: *cleanup_job

cleanup_build_failed:
  stage: cleanup
  needs: ["deploy"]
  when: on_failure
  <<: *cleanup_job

cleanup_inspec_failed:
  stage: cleanup
  needs: ["inspec"]
  when: on_failure
  <<: *cleanup_job